const data = {
    "portuguese":{
        "header About":"Sobre Mim",
        "header Technologys":"Tecnologias",
        "header Projects":"Projetos",
        "area":"Desenvolvedor Júnior",
        "aboutMe Text":"SOBRE MIM!",
        "":"",
        "":"",
        "":"", 
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
    },
    "english":{
        
    }
}
